import React from "react";

import Head from "next/head";
import LoginBlock from "@/auth/LoginBlock/LoginBlock";

export const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginBlock/>
    </>
  );
};

export default LoginPage;
