import Head from "next/head";
import Typography from "antd/es/typography";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography.Title level={2}>Home</Typography.Title>
      
    </>
  );
};

export default Home;
